org: timrbarclay
app: reddlist
# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# The `service` block is the name of the service
service: reddlist

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x

# The `functions` block defines what code to deploy
functions:
  createPlaylist:
    handler: handler.createPlaylist
    events:
      - schedule:
          rate: cron(0 1 * * ? *)
          enabled: true
          input:
            subreddit: progmetal
            playlist: 4b5XLd1E7CoDSpIBxidebe
      - schedule:
          rate: cron(5 1 * * ? *)
          enabled: true
          input:
            subreddit: metal
            playlist: 6pSFm28Oz3hQ7HXolXJHCj
